<?php

namespace Database\Seeders;

use App\Models\Request;
use App\Models\Student;
use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;
use Carbon\Carbon;

class RequestSeeder extends Seeder
{
    use WithoutModelEvents;

    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        $students = Student::all();

        if ($students->isEmpty()) {
            return;
        }

        // $requests =
        //     [

        //         [
        //             'reference' => 'REQ-2026-' . bin2hex(random_bytes(4)),
        //             'student_id' => $students->first()->id,
        //             'type' => 'transcript',
        //             'status' => 'approved',
        //             'comment' => 'Urgent request for transcript submission',
        //             'details' => [
        //                 'number_of_copies' => 2,
        //                 'delivery_method' => 'email',
        //             ],
        //             'submitted_at' => Carbon::now()->subDays(10),
        //             'reviewed_at' => Carbon::now()->subDays(8),
        //         ],
        //         [
        //             'reference' => 'REQ-2026-' . bin2hex(random_bytes(4)),
        //             'student_id' => $students->first()->id,
        //             'type' => 'extension',
        //             'status' => 'in_review',
        //             'comment' => 'Medical reasons requiring extension',
        //             'details' => [
        //                 'assignment_name' => 'Advanced Calculus Project',
        //                 'requested_days' => 5,
        //                 'reason' => 'Hospitalization for emergency surgery',
        //             ],
        //             'submitted_at' => Carbon::now()->subDays(2),
        //             'reviewed_at' => null,
        //         ],
        //         [
        //             'reference' => 'REQ-2026-' . bin2hex(random_bytes(4)),
        //             'student_id' => count($students) > 1 ? $students[1]->id : $students->first()->id,
        //             'type' => 'transfer',
        //             'status' => 'pending',
        //             'comment' => null,
        //             'details' => [
        //                 'destination_program' => 'Computer Science',
        //                 'reason' => 'Career change after internship experience',
        //             ],
        //             'submitted_at' => Carbon::now()->subDays(1),
        //             'reviewed_at' => null,
        //         ],
        //         [
        //             'reference' => 'REQ-2026-' . bin2hex(random_bytes(4)),
        //             'student_id' => count($students) > 1 ? $students[1]->id : $students->first()->id,
        //             'type' => 'withdrawal',
        //             'status' => 'approved',
        //             'comment' => 'Personal circumstances',
        //             'details' => [
        //                 'course_code' => 'PHY102',
        //                 'course_name' => 'Physics II: Electromagnetism',
        //                 'reason' => 'Work schedule conflict',
        //             ],
        //             'submitted_at' => Carbon::now()->subDays(15),
        //             'reviewed_at' => Carbon::now()->subDays(13),
        //         ],
        //         [
        //             'reference' => 'REQ-2026-' . bin2hex(random_bytes(4)),
        //             'student_id' => count($students) > 2 ? $students[2]->id : $students->first()->id,
        //             'type' => 'appeal',
        //             'status' => 'pending',
        //             'comment' => 'Requesting faculty review',
        //             'details' => [
        //                 'course_code' => 'ENG201',
        //                 'grade_received' => 'C-',
        //                 'reason' => 'Exam held during documented illness',
        //             ],
        //             'submitted_at' => Carbon::now()->subDays(3),
        //             'reviewed_at' => null,
        //         ],
        //         [
        //             'reference' => 'REQ-2026-' . bin2hex(random_bytes(4)),
        //             'student_id' => count($students) > 2 ? $students[2]->id : $students->first()->id,
        //             'type' => 'accommodation',
        //             'status' => 'approved',
        //             'comment' => 'Has medical documentation on file',
        //             'details' => [
        //                 'accommodation_type' => 'Extended time for exams',
        //                 'supporting_documentation' => true,
        //                 'description' => 'Registered learning disability requiring 50% extra time',
        //             ],
        //             'submitted_at' => Carbon::now()->subDays(20),
        //             'reviewed_at' => Carbon::now()->subDays(18),
        //         ],
        //         [
        //             'reference' => 'REQ-2026-' . bin2hex(random_bytes(4)),
        //             'student_id' => count($students) > 3 ? $students[3]->id : $students->first()->id,
        //             'type' => 'leave',
        //             'status' => 'in_review',
        //             'comment' => 'Seeking approval for semester abroad',
        //             'details' => [
        //                 'leave_type' => 'academic',
        //                 'start_date' => Carbon::now()->addMonths(2)->format('Y-m-d'),
        //                 'end_date' => Carbon::now()->addMonths(4)->format('Y-m-d'),
        //                 'reason' => 'Exchange program at partner university',
        //             ],
        //             'submitted_at' => Carbon::now()->subDays(5),
        //             'reviewed_at' => null,
        //         ],
        //         [
        //             'reference' => 'REQ-2026-' . bin2hex(random_bytes(4)),
        //             'student_id' => count($students) > 3 ? $students[3]->id : $students->first()->id,
        //             'type' => 'leave',
        //             'status' => 'in_review',
        //             'comment' => 'Seeking approval for semester abroad',
        //             'details' => [
        //                 'leave_type' => 'academic',
        //                 'start_date' => Carbon::now()->addMonths(2)->format('Y-m-d'),
        //                 'end_date' => Carbon::now()->addMonths(4)->format('Y-m-d'),
        //                 'reason' => 'Exchange program at partner university',
        //             ],
        //             'submitted_at' => Carbon::now()->subDays(5),
        //             'reviewed_at' => null,
        //         ],
        //         [
        //             'reference' => 'REQ-2026-' . bin2hex(random_bytes(4)),
        //             'student_id' => count($students) > 3 ? $students[3]->id : $students->first()->id,
        //             'type' => 'leave',
        //             'status' => 'in_review',
        //             'comment' => 'Seeking approval for semester abroad',
        //             'details' => [
        //                 'leave_type' => 'academic',
        //                 'start_date' => Carbon::now()->addMonths(2)->format('Y-m-d'),
        //                 'end_date' => Carbon::now()->addMonths(4)->format('Y-m-d'),
        //                 'reason' => 'Exchange program at partner university',
        //             ],
        //             'submitted_at' => Carbon::now()->subDays(5),
        //             'reviewed_at' => null,
        //         ],
        //         [
        //             'reference' => 'REQ-2026-' . bin2hex(random_bytes(4)),
        //             'student_id' => count($students) > 3 ? $students[3]->id : $students->first()->id,
        //             'type' => 'leave',
        //             'status' => 'in_review',
        //             'comment' => 'Seeking approval for semester abroad',
        //             'details' => [
        //                 'leave_type' => 'academic',
        //                 'start_date' => Carbon::now()->addMonths(2)->format('Y-m-d'),
        //                 'end_date' => Carbon::now()->addMonths(4)->format('Y-m-d'),
        //                 'reason' => 'Exchange program at partner university',
        //             ],
        //             'submitted_at' => Carbon::now()->subDays(5),
        //             'reviewed_at' => null,
        //         ],
        //         [
        //             'reference' => 'REQ-2026-' . bin2hex(random_bytes(4)),
        //             'student_id' => count($students) > 3 ? $students[3]->id : $students->first()->id,
        //             'type' => 'leave',
        //             'status' => 'in_review',
        //             'comment' => 'Seeking approval for semester abroad',
        //             'details' => [
        //                 'leave_type' => 'academic',
        //                 'start_date' => Carbon::now()->addMonths(2)->format('Y-m-d'),
        //                 'end_date' => Carbon::now()->addMonths(4)->format('Y-m-d'),
        //                 'reason' => 'Exchange program at partner university',
        //             ],
        //             'submitted_at' => Carbon::now()->subDays(5),
        //             'reviewed_at' => null,
        //         ],
        //         [
        //             'reference' => 'REQ-2026-' . bin2hex(random_bytes(4)),
        //             'student_id' => count($students) > 3 ? $students[3]->id : $students->first()->id,
        //             'type' => 'leave',
        //             'status' => 'in_review',
        //             'comment' => 'Seeking approval for semester abroad',
        //             'details' => [
        //                 'leave_type' => 'academic',
        //                 'start_date' => Carbon::now()->addMonths(2)->format('Y-m-d'),
        //                 'end_date' => Carbon::now()->addMonths(4)->format('Y-m-d'),
        //                 'reason' => 'Exchange program at partner university',
        //             ],
        //             'submitted_at' => Carbon::now()->subDays(5),
        //             'reviewed_at' => null,
        //         ],
        //         [
        //             'reference' => 'REQ-2026-' . bin2hex(random_bytes(4)),
        //             'student_id' => count($students) > 3 ? $students[3]->id : $students->first()->id,
        //             'type' => 'leave',
        //             'status' => 'in_review',
        //             'comment' => 'Seeking approval for semester abroad',
        //             'details' => [
        //                 'leave_type' => 'academic',
        //                 'start_date' => Carbon::now()->addMonths(2)->format('Y-m-d'),
        //                 'end_date' => Carbon::now()->addMonths(4)->format('Y-m-d'),
        //                 'reason' => 'Exchange program at partner university',
        //             ],
        //             'submitted_at' => Carbon::now()->subDays(5),
        //             'reviewed_at' => null,
        //         ],
        //         [
        //             'reference' => 'REQ-2026-' . bin2hex(random_bytes(4)),
        //             'student_id' => count($students) > 3 ? $students[3]->id : $students->first()->id,
        //             'type' => 'leave',
        //             'status' => 'in_review',
        //             'comment' => 'Seeking approval for semester abroad',
        //             'details' => [
        //                 'leave_type' => 'academic',
        //                 'start_date' => Carbon::now()->addMonths(2)->format('Y-m-d'),
        //                 'end_date' => Carbon::now()->addMonths(4)->format('Y-m-d'),
        //                 'reason' => 'Exchange program at partner university',
        //             ],
        //             'submitted_at' => Carbon::now()->subDays(5),
        //             'reviewed_at' => null,
        //         ],
        //         [
        //             'reference' => 'REQ-2026-' . bin2hex(random_bytes(4)),
        //             'student_id' => count($students) > 3 ? $students[3]->id : $students->first()->id,
        //             'type' => 'leave',
        //             'status' => 'in_review',
        //             'comment' => 'Seeking approval for semester abroad',
        //             'details' => [
        //                 'leave_type' => 'academic',
        //                 'start_date' => Carbon::now()->addMonths(2)->format('Y-m-d'),
        //                 'end_date' => Carbon::now()->addMonths(4)->format('Y-m-d'),
        //                 'reason' => 'Exchange program at partner university',
        //             ],
        //             'submitted_at' => Carbon::now()->subDays(5),
        //             'reviewed_at' => null,
        //         ],
        //         [
        //             'reference' => 'REQ-2026-' . bin2hex(random_bytes(4)),
        //             'student_id' => count($students) > 3 ? $students[3]->id : $students->first()->id,
        //             'type' => 'leave',
        //             'status' => 'in_review',
        //             'comment' => 'Seeking approval for semester abroad',
        //             'details' => [
        //                 'leave_type' => 'academic',
        //                 'start_date' => Carbon::now()->addMonths(2)->format('Y-m-d'),
        //                 'end_date' => Carbon::now()->addMonths(4)->format('Y-m-d'),
        //                 'reason' => 'Exchange program at partner university',
        //             ],
        //             'submitted_at' => Carbon::now()->subDays(5),
        //             'reviewed_at' => null,
        //         ],
        //         [
        //             'reference' => 'REQ-2026-' . bin2hex(random_bytes(4)),
        //             'student_id' => count($students) > 3 ? $students[3]->id : $students->first()->id,
        //             'type' => 'leave',
        //             'status' => 'in_review',
        //             'comment' => 'Seeking approval for semester abroad',
        //             'details' => [
        //                 'leave_type' => 'academic',
        //                 'start_date' => Carbon::now()->addMonths(2)->format('Y-m-d'),
        //                 'end_date' => Carbon::now()->addMonths(4)->format('Y-m-d'),
        //                 'reason' => 'Exchange program at partner university',
        //             ],
        //             'submitted_at' => Carbon::now()->subDays(5),
        //             'reviewed_at' => null,
        //         ],
        //         [
        //             'reference' => 'REQ-2026-' . bin2hex(random_bytes(4)),
        //             'student_id' => count($students) > 3 ? $students[3]->id : $students->first()->id,
        //             'type' => 'leave',
        //             'status' => 'in_review',
        //             'comment' => 'Seeking approval for semester abroad',
        //             'details' => [
        //                 'leave_type' => 'academic',
        //                 'start_date' => Carbon::now()->addMonths(2)->format('Y-m-d'),
        //                 'end_date' => Carbon::now()->addMonths(4)->format('Y-m-d'),
        //                 'reason' => 'Exchange program at partner university',
        //             ],
        //             'submitted_at' => Carbon::now()->subDays(5),
        //             'reviewed_at' => null,
        //         ],
        //         [
        //             'reference' => 'REQ-2026-' . bin2hex(random_bytes(4)),
        //             'student_id' => count($students) > 3 ? $students[3]->id : $students->first()->id,
        //             'type' => 'leave',
        //             'status' => 'in_review',
        //             'comment' => 'Seeking approval for semester abroad',
        //             'details' => [
        //                 'leave_type' => 'academic',
        //                 'start_date' => Carbon::now()->addMonths(2)->format('Y-m-d'),
        //                 'end_date' => Carbon::now()->addMonths(4)->format('Y-m-d'),
        //                 'reason' => 'Exchange program at partner university',
        //             ],
        //             'submitted_at' => Carbon::now()->subDays(5),
        //             'reviewed_at' => null,
        //         ],
        //         [
        //             'reference' => 'REQ-2026-' . bin2hex(random_bytes(4)),
        //             'student_id' => count($students) > 3 ? $students[3]->id : $students->first()->id,
        //             'type' => 'leave',
        //             'status' => 'in_review',
        //             'comment' => 'Seeking approval for semester abroad',
        //             'details' => [
        //                 'leave_type' => 'academic',
        //                 'start_date' => Carbon::now()->addMonths(2)->format('Y-m-d'),
        //                 'end_date' => Carbon::now()->addMonths(4)->format('Y-m-d'),
        //                 'reason' => 'Exchange program at partner university',
        //             ],
        //             'submitted_at' => Carbon::now()->subDays(5),
        //             'reviewed_at' => null,
        //         ],
        //         [
        //             'reference' => 'REQ-2026-' . bin2hex(random_bytes(4)),
        //             'student_id' => count($students) > 3 ? $students[3]->id : $students->first()->id,
        //             'type' => 'leave',
        //             'status' => 'in_review',
        //             'comment' => 'Seeking approval for semester abroad',
        //             'details' => [
        //                 'leave_type' => 'academic',
        //                 'start_date' => Carbon::now()->addMonths(2)->format('Y-m-d'),
        //                 'end_date' => Carbon::now()->addMonths(4)->format('Y-m-d'),
        //                 'reason' => 'Exchange program at partner university',
        //             ],
        //             'submitted_at' => Carbon::now()->subDays(5),
        //             'reviewed_at' => null,
        //         ],
        //         [
        //             'reference' => 'REQ-2026-' . bin2hex(random_bytes(4)),
        //             'student_id' => count($students) > 3 ? $students[3]->id : $students->first()->id,
        //             'type' => 'leave',
        //             'status' => 'in_review',
        //             'comment' => 'Seeking approval for semester abroad',
        //             'details' => [
        //                 'leave_type' => 'academic',
        //                 'start_date' => Carbon::now()->addMonths(2)->format('Y-m-d'),
        //                 'end_date' => Carbon::now()->addMonths(4)->format('Y-m-d'),
        //                 'reason' => 'Exchange program at partner university',
        //             ],
        //             'submitted_at' => Carbon::now()->subDays(5),
        //             'reviewed_at' => null,
        //         ],
        //         [
        //             'reference' => 'REQ-2026-' . bin2hex(random_bytes(4)),
        //             'student_id' => count($students) > 3 ? $students[3]->id : $students->first()->id,
        //             'type' => 'leave',
        //             'status' => 'in_review',
        //             'comment' => 'Seeking approval for semester abroad',
        //             'details' => [
        //                 'leave_type' => 'academic',
        //                 'start_date' => Carbon::now()->addMonths(2)->format('Y-m-d'),
        //                 'end_date' => Carbon::now()->addMonths(4)->format('Y-m-d'),
        //                 'reason' => 'Exchange program at partner university',
        //             ],
        //             'submitted_at' => Carbon::now()->subDays(5),
        //             'reviewed_at' => null,
        //         ],
        //         [
        //             'reference' => 'REQ-2026-' . bin2hex(random_bytes(4)),
        //             'student_id' => count($students) > 3 ? $students[3]->id : $students->first()->id,
        //             'type' => 'leave',
        //             'status' => 'in_review',
        //             'comment' => 'Seeking approval for semester abroad',
        //             'details' => [
        //                 'leave_type' => 'academic',
        //                 'start_date' => Carbon::now()->addMonths(2)->format('Y-m-d'),
        //                 'end_date' => Carbon::now()->addMonths(4)->format('Y-m-d'),
        //                 'reason' => 'Exchange program at partner university',
        //             ],
        //             'submitted_at' => Carbon::now()->subDays(5),
        //             'reviewed_at' => null,
        //         ],
        //         [
        //             'reference' => 'REQ-2026-' . bin2hex(random_bytes(4)),
        //             'student_id' => count($students) > 3 ? $students[3]->id : $students->first()->id,
        //             'type' => 'leave',
        //             'status' => 'in_review',
        //             'comment' => 'Seeking approval for semester abroad',
        //             'details' => [
        //                 'leave_type' => 'academic',
        //                 'start_date' => Carbon::now()->addMonths(2)->format('Y-m-d'),
        //                 'end_date' => Carbon::now()->addMonths(4)->format('Y-m-d'),
        //                 'reason' => 'Exchange program at partner university',
        //             ],
        //             'submitted_at' => Carbon::now()->subDays(5),
        //             'reviewed_at' => null,
        //         ],
        //         [
        //             'reference' => 'REQ-2026-' . bin2hex(random_bytes(4)),
        //             'student_id' => count($students) > 3 ? $students[3]->id : $students->first()->id,
        //             'type' => 'leave',
        //             'status' => 'in_review',
        //             'comment' => 'Seeking approval for semester abroad',
        //             'details' => [
        //                 'leave_type' => 'academic',
        //                 'start_date' => Carbon::now()->addMonths(2)->format('Y-m-d'),
        //                 'end_date' => Carbon::now()->addMonths(4)->format('Y-m-d'),
        //                 'reason' => 'Exchange program at partner university',
        //             ],
        //             'submitted_at' => Carbon::now()->subDays(5),
        //             'reviewed_at' => null,
        //         ],
        //         [
        //             'reference' => 'REQ-2026-' . bin2hex(random_bytes(4)),
        //             'student_id' => count($students) > 3 ? $students[3]->id : $students->first()->id,
        //             'type' => 'leave',
        //             'status' => 'in_review',
        //             'comment' => 'Seeking approval for semester abroad',
        //             'details' => [
        //                 'leave_type' => 'academic',
        //                 'start_date' => Carbon::now()->addMonths(2)->format('Y-m-d'),
        //                 'end_date' => Carbon::now()->addMonths(4)->format('Y-m-d'),
        //                 'reason' => 'Exchange program at partner university',
        //             ],
        //             'submitted_at' => Carbon::now()->subDays(5),
        //             'reviewed_at' => null,
        //         ],
        //         [
        //             'reference' => 'REQ-2026-' . bin2hex(random_bytes(4)),
        //             'student_id' => count($students) > 3 ? $students[3]->id : $students->first()->id,
        //             'type' => 'leave',
        //             'status' => 'in_review',
        //             'comment' => 'Seeking approval for semester abroad',
        //             'details' => [
        //                 'leave_type' => 'academic',
        //                 'start_date' => Carbon::now()->addMonths(2)->format('Y-m-d'),
        //                 'end_date' => Carbon::now()->addMonths(4)->format('Y-m-d'),
        //                 'reason' => 'Exchange program at partner university',
        //             ],
        //             'submitted_at' => Carbon::now()->subDays(5),
        //             'reviewed_at' => null,
        //         ],
        //         [
        //             'reference' => 'REQ-2026-' . bin2hex(random_bytes(4)),
        //             'student_id' => count($students) > 3 ? $students[3]->id : $students->first()->id,
        //             'type' => 'leave',
        //             'status' => 'in_review',
        //             'comment' => 'Seeking approval for semester abroad',
        //             'details' => [
        //                 'leave_type' => 'academic',
        //                 'start_date' => Carbon::now()->addMonths(2)->format('Y-m-d'),
        //                 'end_date' => Carbon::now()->addMonths(4)->format('Y-m-d'),
        //                 'reason' => 'Exchange program at partner university',
        //             ],
        //             'submitted_at' => Carbon::now()->subDays(5),
        //             'reviewed_at' => null,
        //         ],
        //         [
        //             'reference' => 'REQ-2026-' . bin2hex(random_bytes(4)),
        //             'student_id' => count($students) > 3 ? $students[3]->id : $students->first()->id,
        //             'type' => 'leave',
        //             'status' => 'in_review',
        //             'comment' => 'Seeking approval for semester abroad',
        //             'details' => [
        //                 'leave_type' => 'academic',
        //                 'start_date' => Carbon::now()->addMonths(2)->format('Y-m-d'),
        //                 'end_date' => Carbon::now()->addMonths(4)->format('Y-m-d'),
        //                 'reason' => 'Exchange program at partner university',
        //             ],
        //             'submitted_at' => Carbon::now()->subDays(5),
        //             'reviewed_at' => null,
        //         ],
        //         [
        //             'reference' => 'REQ-2026-' . bin2hex(random_bytes(4)),
        //             'student_id' => count($students) > 3 ? $students[3]->id : $students->first()->id,
        //             'type' => 'leave',
        //             'status' => 'in_review',
        //             'comment' => 'Seeking approval for semester abroad',
        //             'details' => [
        //                 'leave_type' => 'academic',
        //                 'start_date' => Carbon::now()->addMonths(2)->format('Y-m-d'),
        //                 'end_date' => Carbon::now()->addMonths(4)->format('Y-m-d'),
        //                 'reason' => 'Exchange program at partner university',
        //             ],
        //             'submitted_at' => Carbon::now()->subDays(5),
        //             'reviewed_at' => null,
        //         ],
        //         [
        //             'reference' => 'REQ-2026-' . bin2hex(random_bytes(4)),
        //             'student_id' => count($students) > 3 ? $students[3]->id : $students->first()->id,
        //             'type' => 'leave',
        //             'status' => 'in_review',
        //             'comment' => 'Seeking approval for semester abroad',
        //             'details' => [
        //                 'leave_type' => 'academic',
        //                 'start_date' => Carbon::now()->addMonths(2)->format('Y-m-d'),
        //                 'end_date' => Carbon::now()->addMonths(4)->format('Y-m-d'),
        //                 'reason' => 'Exchange program at partner university',
        //             ],
        //             'submitted_at' => Carbon::now()->subDays(5),
        //             'reviewed_at' => null,
        //         ],
        //         [
        //             'reference' => 'REQ-2026-' . bin2hex(random_bytes(4)),
        //             'student_id' => count($students) > 3 ? $students[3]->id : $students->first()->id,
        //             'type' => 'leave',
        //             'status' => 'in_review',
        //             'comment' => 'Seeking approval for semester abroad',
        //             'details' => [
        //                 'leave_type' => 'academic',
        //                 'start_date' => Carbon::now()->addMonths(2)->format('Y-m-d'),
        //                 'end_date' => Carbon::now()->addMonths(4)->format('Y-m-d'),
        //                 'reason' => 'Exchange program at partner university',
        //             ],
        //             'submitted_at' => Carbon::now()->subDays(5),
        //             'reviewed_at' => null,
        //         ],
        //         [
        //             'reference' => 'REQ-2026-' . bin2hex(random_bytes(4)),
        //             'student_id' => count($students) > 3 ? $students[3]->id : $students->first()->id,
        //             'type' => 'leave',
        //             'status' => 'in_review',
        //             'comment' => 'Seeking approval for semester abroad',
        //             'details' => [
        //                 'leave_type' => 'academic',
        //                 'start_date' => Carbon::now()->addMonths(2)->format('Y-m-d'),
        //                 'end_date' => Carbon::now()->addMonths(4)->format('Y-m-d'),
        //                 'reason' => 'Exchange program at partner university',
        //             ],
        //             'submitted_at' => Carbon::now()->subDays(5),
        //             'reviewed_at' => null,
        //         ],
        //         [
        //             'reference' => 'REQ-2026-' . bin2hex(random_bytes(4)),
        //             'student_id' => count($students) > 3 ? $students[3]->id : $students->first()->id,
        //             'type' => 'leave',
        //             'status' => 'in_review',
        //             'comment' => 'Seeking approval for semester abroad',
        //             'details' => [
        //                 'leave_type' => 'academic',
        //                 'start_date' => Carbon::now()->addMonths(2)->format('Y-m-d'),
        //                 'end_date' => Carbon::now()->addMonths(4)->format('Y-m-d'),
        //                 'reason' => 'Exchange program at partner university',
        //             ],
        //             'submitted_at' => Carbon::now()->subDays(5),
        //             'reviewed_at' => null,
        //         ],
        //         [
        //             'reference' => 'REQ-2026-' . bin2hex(random_bytes(4)),
        //             'student_id' => count($students) > 3 ? $students[3]->id : $students->first()->id,
        //             'type' => 'leave',
        //             'status' => 'in_review',
        //             'comment' => 'Seeking approval for semester abroad',
        //             'details' => [
        //                 'leave_type' => 'academic',
        //                 'start_date' => Carbon::now()->addMonths(2)->format('Y-m-d'),
        //                 'end_date' => Carbon::now()->addMonths(4)->format('Y-m-d'),
        //                 'reason' => 'Exchange program at partner university',
        //             ],
        //             'submitted_at' => Carbon::now()->subDays(5),
        //             'reviewed_at' => null,
        //         ],
        //         [
        //             'reference' => 'REQ-2026-' . bin2hex(random_bytes(4)),
        //             'student_id' => count($students) > 3 ? $students[3]->id : $students->first()->id,
        //             'type' => 'leave',
        //             'status' => 'in_review',
        //             'comment' => 'Seeking approval for semester abroad',
        //             'details' => [
        //                 'leave_type' => 'academic',
        //                 'start_date' => Carbon::now()->addMonths(2)->format('Y-m-d'),
        //                 'end_date' => Carbon::now()->addMonths(4)->format('Y-m-d'),
        //                 'reason' => 'Exchange program at partner university',
        //             ],
        //             'submitted_at' => Carbon::now()->subDays(5),
        //             'reviewed_at' => null,
        //         ],
        //         [
        //             'reference' => 'REQ-2026-' . bin2hex(random_bytes(4)),
        //             'student_id' => count($students) > 3 ? $students[3]->id : $students->first()->id,
        //             'type' => 'leave',
        //             'status' => 'in_review',
        //             'comment' => 'Seeking approval for semester abroad',
        //             'details' => [
        //                 'leave_type' => 'academic',
        //                 'start_date' => Carbon::now()->addMonths(2)->format('Y-m-d'),
        //                 'end_date' => Carbon::now()->addMonths(4)->format('Y-m-d'),
        //                 'reason' => 'Exchange program at partner university',
        //             ],
        //             'submitted_at' => Carbon::now()->subDays(5),
        //             'reviewed_at' => null,
        //         ],
        //         [
        //             'reference' => 'REQ-2026-' . bin2hex(random_bytes(4)),
        //             'student_id' => count($students) > 3 ? $students[3]->id : $students->first()->id,
        //             'type' => 'leave',
        //             'status' => 'in_review',
        //             'comment' => 'Seeking approval for semester abroad',
        //             'details' => [
        //                 'leave_type' => 'academic',
        //                 'start_date' => Carbon::now()->addMonths(2)->format('Y-m-d'),
        //                 'end_date' => Carbon::now()->addMonths(4)->format('Y-m-d'),
        //                 'reason' => 'Exchange program at partner university',
        //             ],
        //             'submitted_at' => Carbon::now()->subDays(5),
        //             'reviewed_at' => null,
        //         ],
        //         [
        //             'reference' => 'REQ-2026-' . bin2hex(random_bytes(4)),
        //             'student_id' => count($students) > 3 ? $students[3]->id : $students->first()->id,
        //             'type' => 'leave',
        //             'status' => 'in_review',
        //             'comment' => 'Seeking approval for semester abroad',
        //             'details' => [
        //                 'leave_type' => 'academic',
        //                 'start_date' => Carbon::now()->addMonths(2)->format('Y-m-d'),
        //                 'end_date' => Carbon::now()->addMonths(4)->format('Y-m-d'),
        //                 'reason' => 'Exchange program at partner university',
        //             ],
        //             'submitted_at' => Carbon::now()->subDays(5),
        //             'reviewed_at' => null,
        //         ],
        //         [
        //             'reference' => 'REQ-2026-' . bin2hex(random_bytes(4)),
        //             'student_id' => count($students) > 3 ? $students[3]->id : $students->first()->id,
        //             'type' => 'leave',
        //             'status' => 'in_review',
        //             'comment' => 'Seeking approval for semester abroad',
        //             'details' => [
        //                 'leave_type' => 'academic',
        //                 'start_date' => Carbon::now()->addMonths(2)->format('Y-m-d'),
        //                 'end_date' => Carbon::now()->addMonths(4)->format('Y-m-d'),
        //                 'reason' => 'Exchange program at partner university',
        //             ],
        //             'submitted_at' => Carbon::now()->subDays(5),
        //             'reviewed_at' => null,
        //         ],
        //         [
        //             'reference' => 'REQ-2026-' . bin2hex(random_bytes(4)),
        //             'student_id' => count($students) > 3 ? $students[3]->id : $students->first()->id,
        //             'type' => 'leave',
        //             'status' => 'in_review',
        //             'comment' => 'Seeking approval for semester abroad',
        //             'details' => [
        //                 'leave_type' => 'academic',
        //                 'start_date' => Carbon::now()->addMonths(2)->format('Y-m-d'),
        //                 'end_date' => Carbon::now()->addMonths(4)->format('Y-m-d'),
        //                 'reason' => 'Exchange program at partner university',
        //             ],
        //             'submitted_at' => Carbon::now()->subDays(5),
        //             'reviewed_at' => null,
        //         ],
        //         [
        //             'reference' => 'REQ-2026-' . bin2hex(random_bytes(4)),
        //             'student_id' => count($students) > 3 ? $students[3]->id : $students->first()->id,
        //             'type' => 'leave',
        //             'status' => 'in_review',
        //             'comment' => 'Seeking approval for semester abroad',
        //             'details' => [
        //                 'leave_type' => 'academic',
        //                 'start_date' => Carbon::now()->addMonths(2)->format('Y-m-d'),
        //                 'end_date' => Carbon::now()->addMonths(4)->format('Y-m-d'),
        //                 'reason' => 'Exchange program at partner university',
        //             ],
        //             'submitted_at' => Carbon::now()->subDays(5),
        //             'reviewed_at' => null,
        //         ],
        //         [
        //             'reference' => 'REQ-2026-' . bin2hex(random_bytes(4)),
        //             'student_id' => count($students) > 3 ? $students[3]->id : $students->first()->id,
        //             'type' => 'leave',
        //             'status' => 'in_review',
        //             'comment' => 'Seeking approval for semester abroad',
        //             'details' => [
        //                 'leave_type' => 'academic',
        //                 'start_date' => Carbon::now()->addMonths(2)->format('Y-m-d'),
        //                 'end_date' => Carbon::now()->addMonths(4)->format('Y-m-d'),
        //                 'reason' => 'Exchange program at partner university',
        //             ],
        //             'submitted_at' => Carbon::now()->subDays(5),
        //             'reviewed_at' => null,
        //         ],
        //         [
        //             'reference' => 'REQ-2026-' . bin2hex(random_bytes(4)),
        //             'student_id' => count($students) > 3 ? $students[3]->id : $students->first()->id,
        //             'type' => 'leave',
        //             'status' => 'in_review',
        //             'comment' => 'Seeking approval for semester abroad',
        //             'details' => [
        //                 'leave_type' => 'academic',
        //                 'start_date' => Carbon::now()->addMonths(2)->format('Y-m-d'),
        //                 'end_date' => Carbon::now()->addMonths(4)->format('Y-m-d'),
        //                 'reason' => 'Exchange program at partner university',
        //             ],
        //             'submitted_at' => Carbon::now()->subDays(5),
        //             'reviewed_at' => null,
        //         ],
        //     ];

        // foreach ($requests as $request) {
        //     Request::create($request);
        // }

        // Generate additional random requests
        Request::factory(15)->create();
    }
}
